# Create the clause checker (advanced checking for singletons):
checker:
	tar cf checker.tar checker.pl clause_verification.pl \
		compatibility_utilities_swi.pl higher_order.pl \
		utilities.pl set_in_list.pl vardict_utilities.pl \
		io_utilities.pl errors_and_warnings.pl boolean_operations.pl
	gzip  checker.tar
