
clean:
	rm -f *.O *.xwam core *~ *.bak .#* *.dll *.obj *.lib *.def *.exp
	rm -f */*.O */*.xwam */core */*~ */*.bak */.#* */*.dll */*.obj */*.lib */*.def */*.exp
	rm -f */*/*.O */*/*.xwam */*/core */*/*~ */*/*.bak */*/*/.#* */*/*.dll */*/*.obj */*/*.lib */*/*.def */*/*.exp
	rm -f ../XSB/packages/*.xwam ../XSB/packages/*/*.xwam ../XSB/packages/*/*/*.xwam 
